services:
  frontend:
    build:
      target: dependencies
    command: npm run start -- --host 0.0.0.0 --poll=1000
    environment:
      NODE_ENV: development
    depends_on:
      backend:
        condition: service_started
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    healthcheck:
      disable: true

  backend:
    build:
      target: dependencies
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    environment:
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:4200
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    healthcheck:
      disable: true

volumes:
  frontend-node-modules:
  backend-node-modules:
