services:
  frontend:
    build:
      target: dependencies
    command: npm run start -- --host 0.0.0.0 --poll=1000
    environment:
      NODE_ENV: development
    depends_on:
      backend:
        condition: service_started
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    healthcheck:
      disable: true

  backend:
    build:
      target: development
    command: cargo run --locked
    environment:
      APP_ENV: dev
      REDIS_URL: redis://redis:6379
      OPENSEARCH_NODE: http://opensearch:9200
      CORS_ORIGIN: http://localhost:4200
    volumes:
      - ./backend:/app
      - backend-cargo-registry:/usr/local/cargo/registry
      - backend-target:/app/target
    healthcheck:
      disable: true

volumes:
  frontend-node-modules:
  backend-cargo-registry:
  backend-target:
